### PR TITLE
Update Maintainers

### PR DESCRIPTION
**Pull request by SteveLasker**
Thanks to @kaywilliams and @kkarunakaran89 for helping to establish the SCITT Community.

### CODE REVIEW

**Review by OR13 — APPROVED** [review]

**Review by yogeshbdeshpande — APPROVED** [review]
LGTM!

**Review by JAG-UK — APPROVED** [review]
Definitely approve AJ. Great addition!

**Comment by SteveLasker** [comment]
Votes pass:
Welcome @aj-stein

**Review by xee5ch — COMMENTED** [review]
Looks good to me, if not a bit ironic.

**Review by aj-stein — COMMENTED** [review]
Looks good to me, if not a bit ironic.

**Pull request merged**
